config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  get 'tweets/:tweet_id/likes' => 'likes#create'
  get 'tweets/:tweet_id/likes/:id' => 'likes#destroy'
  
  resources :tweets do
   resources :likes, only: [:create, :destroy]
   resources :comments, only: [:create]

  end

  
  root 'tweets#index'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates_uniqueness_of :tweet_id, scope: :user_id
  
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  #Tagsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :tweets, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
     has_many :tweet_tag_relations, dependent: :destroy
     has_many :tags, through: :tweet_tag_relations, dependent: :destroy
     mount_uploader :image, ImageUploader
   
     belongs_to :user
     has_many :likes, dependent: :destroy
     has_many :liked_users, through: :likes, source: :user
     has_many :comments, dependent: :destroy
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :comments, dependent: :destroy

  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    else  
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
   end

  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end 
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
 def create
    like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
    redirect_back(fallback_location: root_path)
 end

 def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
 end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
    def index
        @tweet = Tweet.all

      if params[:tag_ids]
       @tweet = []
       params[:tag_ids].each do |key, value|      
        @tweet += Tag.find_by(name: key).tweets if value == "1"
      end
      @tweet.uniq!
    end

      if params[:tag]
       Tag.create(name: params[:tag])
      end
    end
      def new
        @tweet = Tweet.new
      end
  

  def create
    tweet = Tweet.new(tweet_params)
    
    tweet.user_id = current_user.id

    if tweet.save!
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments
    @comment = Comment.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
    
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  private
  def tweet_params
    params.require(:tweet).permit(:name, :gunma, :image, :point, :lat, :lng, tag_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>tcueroute</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/c2990014c4.js"  crossorigin="anonymous"></script> 

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<body>
 <header>
  <h1>tcueroute</h1>
  <div class="header-list">
   <ul>
    <% if user_signed_in? %>
     <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
     <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>
 </header>
 <main>
  <%= yield %>
 </main>
     <footer>
      <p>Copyright © GeekSalon All Rights Reserved.</p>
    </footer>
</body>

</html>

app/views/tweets/edit.html.erb
<%= stylesheet_link_tag 'edit', :media => "all" %>

<div class="post-container">
<p class="title">投稿編集ページ</post>
<%= form_for(@tweet, :url => { controller:'tweets', action:'edit'}) do |f| %>
    <%= f.label :投稿内容 %>
        <br>
        <%= f.text_field :body,size: 140%>
        <br>
  <div class="field">
    <%= f.label :分類  %>
    <%= f.select :gunma, 
    [["車", "車"], 
    ["自転車", "自転車"], 
    ["歩行者", "歩行者"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :補足説明  %>
    <%= f.text_area :point, :size => "30x2" %>
  </div>

    <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
    </div>




  <div class="actions">
    <%= f.label :body,"内容" %>
    <%= f.text_field :body %>
    <%= f.label :lat,"緯度" %>
    <%= f.text_field :lat, id: :lat %>
    <%= f.label :lng,"経度" %>
    <%= f.text_field :lng, id: :lng %>
  </div>

  
<h2>Map</h2>

<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="検索" onclick="codeAddress()">
<p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
let map
let marker
function initMap(){

  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: 36.345813969592186, lng:138.97702695767177l},  //高崎経済大学
    zoom: 13,
    
  });
}

let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('address').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      
        if (aft == true){
            marker.setMap(null);
        }

      
        map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            draggable: true
        });

        aft = true

        //検索した時に緯度経度を入力する
        document.getElementById('lat').value = results[0].geometry.location.lat();
        document.getElementById('lng').value = results[0].geometry.location.lng();

        // マーカーのドロップ（ドラッグ終了）時のイベント
        google.maps.event.addListener( marker, 'dragend', function(ev){
            // イベントの引数evの、プロパティ.latLngが緯度経度
            document.getElementById('lat').value = ev.latLng.lat();
            document.getElementById('lng').value = ev.latLng.lng();
        });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBuX6sKPiMZ2DdDvI24w_PfSgZeAPxnrxA&callback=initMap" async defer></script>

<%= f.submit "編集する" %>
<% end %>

<%= link_to "Mapに戻る", tweets_path %>
<br>

</div>

app/views/tweets/index.html.erb
<h1>通学路危険MAP</h1>

<h2>gmap</h2>

<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="Encode" onclick="codeAddress()">

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
    function initMap() {
    //初期表示位置
      let latlng = new google.maps.LatLng(36.33998499840244, 138.99091007153316);
      //デザイン
      let styles = [
           {
            stylers: [
             { "saturation": 0 },
             { "lightness": 0 }
            ]
           }
          ];

      let map = new google.maps.Map(document.getElementById('map'), {
          zoom: 5.5,
          styles: styles,
          center: latlng
      });
      let transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);

        <% @tweet.each do |t| %>
        ( function() { 
         let markerLatLng = { lat: <%= t.lat %>, lng: <%= t.lng %> }; 
        
        let marker = new google.maps.Marker({ 
        position: markerLatLng, 
        map: map 
//マーカーをクリックしたとき、詳細情報を表示
          let infowindow = new google.maps.InfoWindow({
            position: markerLatLng,
            content: "<a href='<%= tweet_url(t.id) %>' target='_blank'></a>"
          }); //ここで詳細ページへのリンクを表示させる
          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });
    })();
   <% end %>
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBuX6sKPiMZ2DdDvI24w_PfSgZeAPxnrxA&callback=initMap" async defer></script>

<%= stylesheet_link_tag 'index', :media => "all" %>

<div class="tweets-container">
<h3>一覧ページ</h3>
<%= link_to "新規投稿へ", new_tweet_path %>
  <% @tweet.each do |t| %>
    <div class="tweet">
     <div class="main-box">
      <div class="left-container"><%= t.body %></div>
      <div class="right-container">
      <%= t.user.email %>
    
      <%= image_tag t.image_url, size: "250x200" if t.image? %>

      <%= t.created_at %>
      <%= t.name %>
      <%= t.gunma %>
      
      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
          <i class="fas fa-heart" style="color:red;"></i><%= t.likes.count %>
      <% end %>

      <% else %>
          <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
              <i class="far fa-heart" style="color:red;"></i><%= t.likes.count %>
          <% end %>
      <% end %>

      <% else %>
      <i class="far fa-heart" style="color:red;"></i><%= t.likes.count %>
      <% end %>
      
      <%= t.point %>
      <%= link_to "詳細へ", tweet_path(t.id) %> 
      <%= button_to "削除する", tweet_path(t.id), method: :delete %>
    </div>
  <% end %>
</div>
      <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
        <% Tag.all.each do |t| %>
          <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
        <% end %>
       <% end %>
 <%= submit_tag '検索' %>

<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
    <%= text_field_tag :tag %>
    <%= submit_tag 'タグを追加' %>

<% end %>

app/views/tweets/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>

<div class="post-container">
 <p class="title">新規投稿ページ</p>
 <%= form_for(@tweet, :url => { controller:'tweets', action:'create'})do |f| %>
 <%= f.label :投稿内容 %>
      <br>
      <%= f.text_field :body,size: 140%>
      <br>

  <div class="field">
  <%= f.label :分類  %>
 
    <%= f.select :gunma, 
    [["車", "車"], 
    ["自転車", "自転車"], 
    ["歩行者", "歩行者"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= f.label :画像 %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :画像への補足説明  %>
    <%= f.text_area :point, :size => "30x2" %>
  </div>

    <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
    </div>

<%= form_with(model: @tweet, local: true) do |f| %>
  <div class="actions">
    <%= f.label :body,"場所" %>
    <%= f.text_field :body %>
    <%= f.label :lat,"緯度" %>
    <%= f.text_field :lat,:value =>"緯度", id: :lat %>
    <%= f.label :lng,"経度" %>
    <%= f.text_field :lng,:value =>"経度", id: :lng %>

　<h2>Map</h2>

<input id="address" type="textbox" value="　">
<input type="button" value="検索" onclick="codeAddress()">
<p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
let map
let marker
function initMap(){

  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: 36.345813969592186, lng:138.97702695767177, },  //高崎経済大学
    zoom: 13,
    
  });
}

let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('address').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      
        if (aft == true){
            marker.setMap(null);
        }

      
        map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            draggable: true
        });

        aft = true

        //検索した時に緯度経度を入力する
        document.getElementById('lat').value = results[0].geometry.location.lat();
        document.getElementById('lng').value = results[0].geometry.location.lng();

        // マーカーのドロップ（ドラッグ終了）時のイベント
        google.maps.event.addListener( marker, 'dragend', function(ev){
            // イベントの引数evの、プロパティ.latLngが緯度経度
            document.getElementById('lat').value = ev.latLng.lat();
            document.getElementById('lng').value = ev.latLng.lng();
        });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBuX6sKPiMZ2DdDvI24w_PfSgZeAPxnrxA&callback=initMap" async defer></script>

  <%= f.submit %>
  </div>
<% end %>

<%= link_to "Mapに戻る", tweets_path %>
<br>
<% end %>
</div>

app/views/tweets/show.html.erb
<h1>通学路危険MAP</h1>
<h3>投稿詳細</h3>
<div class="tweet">
  <p><%= @tweet.gunma %></p>
  <p><%= @tweet.created_at %></p>

  <% @tweet.tags.each do |tag| %>
    <span><%= tag.name %></span>
  <% end %>

<% if user_signed_in? %>
      <% if current_user.already_liked?(@tweet) %>
        <%= link_to tweet_like_path(@tweet), method: :delete do %>
          <p>いいねを取り消す</p><%= @tweet.likes.count %>
       <% end %>
      <% else %>
        <%= link_to tweet_likes_path(@tweet), method: :post do %>
          <i class="far fa-heart" style="color:red;"></i><%= @tweet.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <i class="far fa-heart" style="color:red;"></i><%= @tweet.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_tweet_path(@tweet.id) %>
</div>

<div id='map'></div>
<style>
#map {
  height: 600px;
  width: 100%;
}
</style>

<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: <%= @tweet.lat %>, lng: <%= @tweet.lng %>},
    zoom: 15,
  });

   marker = new google.maps.Marker({
    position:  {lat: <%= @tweet.lat %>, lng: <%= @tweet.lng %>},
    map: map
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBuX6sKPiMZ2DdDvI24w_PfSgZeAPxnrxA&callback=initMap" async defer></script>

<h2>いいねしたユーザー</h2>
<% @tweet.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>
    <% if user_signed_in? %>
    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "MAPに戻る", tweets_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>